# PARTICLES_BULLET_EXPLODE_AMOUNT = 30
PARTICLES_BULLET_EXPLODE_AMOUNT = 40
# PARTICLES_BULLET_EXPLODE_DURATION = 0.15
PARTICLES_BULLET_EXPLODE_DURATION = 15 / 50
PARTICLES_BULLET_EXPLODE_SPEED = 1
PARTICLE_BULLET_EXPLODE_SIZE = 1

PARTICLES_BULLET_MOVE_AMOUNT = 10
PARTICLES_BULLET_MOVE_DURATION = 40 / 50
PARTICLES_BULLET_MOVE_SPEED = 0.1
PARTICLE_BULLET_MOVE_SIZE = 0.5
