"""
This module defines constants associated with range fighter.
"""

RANGER_SPEED = 2
RANGER_ATTACK_RANGE = 25
RANGER_DAMAGE = 50
RANGER_HEALTH = 200
RANGER_VISION = 30
RANGER_ABILITIES_CD = 1.5
RANGER_ABILITIES_RADIUS = 100
RANGER_ATTACK_SPEED = 1
